// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('buscasmartphone', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('buscasmartphone', async function() {
    await driver.get("https://www.submarino.com.br/")
    await driver.manage().window().setRect(1366, 728)
    await driver.findElement(By.id("h_search-input")).click()
    {
      const element = await driver.findElement(By.id("h_search-btn"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    await driver.findElement(By.id("h_search-input")).sendKeys("Smartphone samsung galaxy")
    await driver.findElement(By.id("h_search-btn")).click()
    await driver.findElement(By.css(".col__StyledCol-sc-1snw5v3-0:nth-child(1) .src__Image-xr9q25-0")).click()
    await driver.executeScript("window.scrollTo(0,185)")
    await driver.executeScript("window.scrollTo(0,399)")
    await driver.findElement(By.id("h_search-input")).click()
    await driver.findElement(By.id("h_search-input")).sendKeys("smartphone motorola one vision")
    await driver.findElement(By.id("h_search-btn")).click()
    await driver.findElement(By.css(".col__StyledCol-sc-1snw5v3-0:nth-child(1) .src__Image-xr9q25-0")).click()
    await driver.executeScript("window.scrollTo(0,426)")
    await driver.findElement(By.id("h_search-input")).click()
    await driver.findElement(By.id("h_search-input")).sendKeys("smartphone xiaomi")
    await driver.findElement(By.id("h_search-btn")).click()
    await driver.findElement(By.css(".col__StyledCol-sc-1snw5v3-0:nth-child(1) a > .src__Text-sc-154pg0p-0")).click()
    await driver.executeScript("window.scrollTo(0,97)")
  })
})
